# Generated by Django 2.1.2 on 2018-11-17 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ConfLevelCounter',
            fields=[
                ('conf_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fileserver.ConfLevel')),
                ('total_docs', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DoctypeCounter',
            fields=[
                ('doctype', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fileserver.Doctype')),
                ('total_docs', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCounter',
            fields=[
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fileserver.Language')),
                ('total_docs', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='conf_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileserver.ConfLevel'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='doctype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileserver.Doctype'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileserver.Language'),
        ),
    ]
